app:
  name: campus-project-hub-api
  env: development
  port: 8000
  debug: true

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: campus_project_hub
  sslmode: disable

jwt:
  secret: your-super-secret-jwt-key
  expiry_hours: 24
  refresh_expiry_hours: 168

oauth:
  google:
    client_id: ""
    client_secret: ""
    redirect_url: "http://localhost:8000/api/v1/auth/google/callback"
  github:
    client_id: ""
    client_secret: ""
    redirect_url: "http://localhost:8000/api/v1/auth/github/callback"

midtrans:
  server_key: ""
  client_key: ""
  is_production: false

upload:
  dir: ./uploads
  max_size: 10485760

cors:
  frontend_url: "http://localhost:3000"
